#!/usr/bin/env bun

import { $ } from "bun"
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"
import solidPlugin from "../node_modules/@opentui/solid/scripts/solid-plugin"
import { Archive } from "../src/util/archive"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

import { Script } from "@slopcode-ai/script"
import pkg from "../package.json"

const modelsUrl = process.env.SLOPCODE_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.ts"),
  `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
)
console.log("Generated models-snapshot.ts")

// Load migrations from migration directories
const migrationDirs = (
  await fs.promises.readdir(path.join(dir, "migration"), {
    withFileTypes: true,
  })
)
  .filter((entry) => entry.isDirectory() && /^\d{4}\d{2}\d{2}\d{2}\d{2}\d{2}/.test(entry.name))
  .map((entry) => entry.name)
  .sort()

const migrations = await Promise.all(
  migrationDirs.map(async (name) => {
    const file = path.join(dir, "migration", name, "migration.sql")
    const sql = await Bun.file(file).text()
    const match = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(name)
    const timestamp = match
      ? Date.UTC(
          Number(match[1]),
          Number(match[2]) - 1,
          Number(match[3]),
          Number(match[4]),
          Number(match[5]),
          Number(match[6]),
        )
      : 0
    return { sql, timestamp }
  }),
)
console.log(`Loaded ${migrations.length} migrations`)

const singleFlag = process.argv.includes("--single")
const baselineFlag = process.argv.includes("--baseline")
const skipInstall = process.argv.includes("--skip-install")

const nvimVersion = "v0.12.1"
const nvimBinary = (os: string) => (os === "win32" ? "nvim.exe" : "nvim")
const nvimAssets = {
  "linux-x64": {
    name: "nvim-linux-x86_64.tar.gz",
    url: `https://github.com/neovim/neovim/releases/download/${nvimVersion}/nvim-linux-x86_64.tar.gz`,
    sha256: "ab757a1fd9ad307d53d2df4045698906a7ca3993d92260dd8fe49108712d57d0",
    format: "tar",
  },
  "linux-arm64": {
    name: "nvim-linux-arm64.tar.gz",
    url: `https://github.com/neovim/neovim/releases/download/${nvimVersion}/nvim-linux-arm64.tar.gz`,
    sha256: "a3f8aa5590fd2ac930bcc5c9070b9ac1ec33461d262b6428874c5fc640f3f13c",
    format: "tar",
  },
  "darwin-x64": {
    name: "nvim-macos-x86_64.tar.gz",
    url: `https://github.com/neovim/neovim/releases/download/${nvimVersion}/nvim-macos-x86_64.tar.gz`,
    sha256: "e59a5eafcdf824e2bf6a738e75f8f62ba4ff1b7f1c7daaec2d134aa46737907c",
    format: "tar",
  },
  "darwin-arm64": {
    name: "nvim-macos-arm64.tar.gz",
    url: `https://github.com/neovim/neovim/releases/download/${nvimVersion}/nvim-macos-arm64.tar.gz`,
    sha256: "b77e01c5421ac1bac593eed5c2ea1b950439306dd4c32371ac2473792da9a9d5",
    format: "tar",
  },
  "win32-x64": {
    name: "nvim-win64.zip",
    url: `https://github.com/neovim/neovim/releases/download/${nvimVersion}/nvim-win64.zip`,
    sha256: "75fedc530b3772ca9f177edc7db92560bb9d2d6700ac6d5b2c53eaf5a9317ae3",
    format: "zip",
  },
} as const

const nvimCache = path.join(dir, "dist", ".neovim-cache")
const nvimDownloads = new Map<string, Promise<string>>()

const nvimKey = (item: { os: string; arch: "arm64" | "x64"; abi?: "musl" }) => {
  if (item.abi === "musl") return
  const key = `${item.os}-${item.arch}` as keyof typeof nvimAssets
  if (key in nvimAssets) return key
}

const nvimDownload = (key: keyof typeof nvimAssets) => {
  const existing = nvimDownloads.get(key)
  if (existing) return existing
  const task = (async () => {
    const asset = nvimAssets[key]
    const out = path.join(nvimCache, asset.name)
    await fs.promises.mkdir(nvimCache, { recursive: true })
    if (!(await Bun.file(out).exists())) {
      const res = await fetch(asset.url)
      if (!res.ok) {
        throw new Error(`Failed to download ${asset.url}: ${res.status} ${res.statusText}`)
      }
      await Bun.write(out, await res.arrayBuffer())
    }
    const digest = new Bun.CryptoHasher("sha256").update(await Bun.file(out).arrayBuffer()).digest("hex")
    if (digest !== asset.sha256) {
      throw new Error(`Neovim digest mismatch for ${asset.name}`)
    }
    return out
  })()
  nvimDownloads.set(key, task)
  return task
}

const nvimBundle = async (item: { os: string; arch: "arm64" | "x64"; abi?: "musl" }, name: string) => {
  const key = nvimKey(item)
  if (!key) return
  const asset = nvimAssets[key]
  const file = await nvimDownload(key)
  const dest = path.join(dir, "dist", name, "bin", "neovim")
  await fs.promises.rm(dest, { recursive: true, force: true })
  await fs.promises.mkdir(dest, { recursive: true })
  if (asset.format === "tar") {
    await $`tar -xzf ${file} -C ${dest} --strip-components=1`
  } else {
    const tmp = path.join(nvimCache, `${asset.name}.tmp`)
    await fs.promises.rm(tmp, { recursive: true, force: true })
    await fs.promises.mkdir(tmp, { recursive: true })
    await Archive.extractZip(file, tmp)
    const entries = await fs.promises.readdir(tmp, { withFileTypes: true })
    const source = entries.length === 1 && entries[0]?.isDirectory() ? path.join(tmp, entries[0].name) : tmp
    await fs.promises.cp(source, dest, { recursive: true, force: true })
    await fs.promises.rm(tmp, { recursive: true, force: true })
  }
}

const allTargets: {
  os: string
  arch: "arm64" | "x64"
  abi?: "musl"
  avx2?: false
}[] = [
  {
    os: "linux",
    arch: "arm64",
  },
  {
    os: "linux",
    arch: "x64",
  },
  {
    os: "linux",
    arch: "x64",
    avx2: false,
  },
  {
    os: "linux",
    arch: "arm64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
    avx2: false,
  },
  {
    os: "darwin",
    arch: "arm64",
  },
  {
    os: "darwin",
    arch: "x64",
  },
  {
    os: "darwin",
    arch: "x64",
    avx2: false,
  },
  {
    os: "win32",
    arch: "x64",
  },
  {
    os: "win32",
    arch: "x64",
    avx2: false,
  },
]

const targets = singleFlag
  ? allTargets.filter((item) => {
      if (item.os !== process.platform || item.arch !== process.arch) {
        return false
      }

      // When building for the current platform, prefer a single native binary by default.
      // Baseline binaries require additional Bun artifacts and can be flaky to download.
      if (item.avx2 === false) {
        return baselineFlag
      }

      // also skip abi-specific builds for the same reason
      if (item.abi !== undefined) {
        return false
      }

      return true
    })
  : allTargets

await $`rm -rf dist`

const binaries: Record<string, string> = {}
if (!skipInstall) {
  await $`bun install --os="*" --cpu="*" @opentui/core@${pkg.dependencies["@opentui/core"]}`
  await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`
}
for (const item of targets) {
  const name = [
    pkg.name,
    // changing to win32 flags npm for some reason
    item.os === "win32" ? "windows" : item.os,
    item.arch,
    item.avx2 === false ? "baseline" : undefined,
    item.abi === undefined ? undefined : item.abi,
  ]
    .filter(Boolean)
    .join("-")
  console.log(`building ${name}`)
  await $`mkdir -p dist/${name}/bin`

  const parserWorker = fs.realpathSync(path.resolve(dir, "./node_modules/@opentui/core/parser.worker.js"))
  const workerPath = "./src/cli/cmd/tui/worker.ts"

  // Use platform-specific bunfs root path based on target OS
  const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"
  const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")

  const result = await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [solidPlugin],
    sourcemap: "external",
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: name.replace(pkg.name, "bun") as any,
      outfile: `dist/${name}/bin/slopcode`,
      execArgv: [`--user-agent=slopcode/${Script.version}`, "--use-system-ca", "--"],
      windows: {},
    },
    entrypoints: ["./src/index.ts", parserWorker, workerPath],
    define: {
      SLOPCODE_VERSION: `'${Script.version}'`,
      SLOPCODE_NVIM_VERSION: `'${nvimVersion}'`,
      SLOPCODE_MIGRATIONS: JSON.stringify(migrations),
      OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
      SLOPCODE_WORKER_PATH: workerPath,
      SLOPCODE_CHANNEL: `'${Script.channel}'`,
      SLOPCODE_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
    },
  })

  if (!result.success) {
    throw new Error(`Build failed for ${name}`)
  }
  if (!(await Bun.file(`dist/${name}/bin/slopcode`).exists())) {
    throw new Error(`Missing built binary at dist/${name}/bin/slopcode`)
  }

  await $`rm -rf ./dist/${name}/bin/tui`
  await nvimBundle(item, name)
  if (item.abi !== "musl") {
    const file = `dist/${name}/bin/neovim/bin/${nvimBinary(item.os)}`
    if (!(await Bun.file(file).exists())) {
      throw new Error(`Missing bundled Neovim at ${file}`)
    }
  }
  await Bun.file(`dist/${name}/package.json`).write(
    JSON.stringify(
      {
        name,
        version: Script.version,
        repository: {
          type: "git",
          url: "https://github.com/teamslop/slopcode",
        },
        os: [item.os],
        cpu: [item.arch],
      },
      null,
      2,
    ),
  )
  binaries[name] = Script.version
}

const debVersion = (() => {
  const version = Script.version.replace(/^v/, "")
  if (!version) {
    return "0.0.0-1"
  }
  if (version.includes(":")) {
    return version
  }
  if (/-\d+$/.test(version)) {
    return version
  }
  return `${version.replace(/-/g, "~")}-1`
})()

const debBuild = async (src: string, arch: "amd64" | "arm64") => {
  const binary = path.join(dir, "dist", src, "bin", "slopcode")
  const nvim = path.join(dir, "dist", src, "bin", "neovim")
  if (!fs.existsSync(binary)) {
    throw new Error(`Missing Debian source binary at ${binary}`)
  }

  const root = path.join(dir, "dist", `deb-${arch}`)
  const binDir = path.join(root, "usr", "bin")
  const libDir = path.join(root, "usr", "lib", "slopcode")
  const controlDir = path.join(root, "DEBIAN")
  const deb = path.join(dir, "dist", `slopcode-linux-${arch}.deb`)

  await fs.promises.rm(root, { recursive: true, force: true })
  await fs.promises.mkdir(binDir, { recursive: true })
  await fs.promises.mkdir(libDir, { recursive: true })
  await fs.promises.mkdir(controlDir, { recursive: true })

  await $`cp ${binary} ${path.join(binDir, "slopcode")}`
  await $`chmod 755 ${path.join(binDir, "slopcode")}`
  if (fs.existsSync(nvim)) {
    await fs.promises.cp(nvim, path.join(libDir, "neovim"), { recursive: true, force: true })
  }

  await Bun.write(
    path.join(controlDir, "control"),
    [
      "Package: slopcode",
      `Version: ${debVersion}`,
      "Section: utils",
      "Priority: optional",
      `Architecture: ${arch}`,
      "Maintainer: SlopCode Team <support@slopcode.dev>",
      "Depends: libc6, libstdc++6",
      "Description: The open source AI slopcoding agent",
      " SlopCode is an open source AI slopcoding agent focused on terminal workflows.",
      "",
    ].join("\n"),
  )

  await $`dpkg-deb --build --root-owner-group ${root} ${deb}`
  await fs.promises.rm(root, { recursive: true, force: true })
}

if (Script.release) {
  const winget = `${pkg.name}-windows-x64-baseline`
  const exe = path.join(dir, "dist", winget, "bin", "slopcode.exe")
  if (!fs.existsSync(exe)) {
    throw new Error(`Missing Winget executable at ${exe}`)
  }

  for (const key of Object.keys(binaries)) {
    if (key.includes("linux")) {
      await $`tar -czf ../../${key}.tar.gz *`.cwd(`dist/${key}/bin`)
      continue
    }

    await $`zip -r ../../${key}.zip *`.cwd(`dist/${key}/bin`)
  }

  await $`tar -czf slopcode-cli-dist.tar.gz ${Object.keys(binaries)}`.cwd("dist")

  if (process.platform === "linux") {
    const dpkgDeb = (await $`bash -lc "command -v dpkg-deb"`.quiet().nothrow().text()).trim()
    if (!dpkgDeb) {
      throw new Error("dpkg-deb is required to build Debian packages")
    }
    await debBuild(`${pkg.name}-linux-x64-baseline`, "amd64")
    await debBuild(`${pkg.name}-linux-arm64`, "arm64")
    await $`gh release upload v${Script.version} ./dist/*.zip ./dist/*.tar.gz ./dist/*.deb --clobber --repo ${process.env.GH_REPO}`
  } else {
    await $`gh release upload v${Script.version} ./dist/*.zip ./dist/*.tar.gz --clobber --repo ${process.env.GH_REPO}`
  }
}

export { binaries }
